### ISSUE TITLE
Support for local dependencies

### ISSUE THREAD

**Issue by montogeek** [bahmutov/next-update#111]
Hi!
I just come to a project that uses local dependencies: `"e2-scripts-utils": "file:../../lib/utils"`, when running `next-update`, it fails with the following error:
```js
Problem checking NPM dependency e2-scripts-utils version file:../../lib/utils
Invalid comparator: file:../../lib/utils
```

Looks like it does not support local dependencies, is there a way to ignore them or something?

Thanks!

**Comment by bahmutov** [comment]
Hmm, it should probably skip `file:...` dependencies.

**Comment by bahmutov** [comment]
Can you provide more details? I tested this in  test/test-file-deps against latest version and it seems to skip these by default

**Comment by montogeek** [comment]
The project works, but `next-update` tries to install it again (run `npm i`), at some point it returns this error:
```
cannot find file /Users/montogeek/project/node_modules/e2-scripts-utils/package.json
ERROR: cannot find module e2-scripts-utils
ERROR testing next working updates
Error: Current installation is incomplete. Please run `npm install` or `bower install` first
    at /Users/montogeek/.nvm/versions/node/v7.7.4/lib/node_modules/next-update/src/next-update.js:51:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at checkCurrentInstall (/Users/montogeek/.nvm/versions/node/v7.7.4/lib/node_modules/next-update/src/next-update.js:69:10)
    at Object.<anonymous> (/Users/montogeek/.nvm/versions/node/v7.7.4/lib/node_modules/next-update/bin/next-update.js:91:3)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3
```
