### ISSUE TITLE
Error: timed out waiting for NPM after 10000ms

### ISSUE THREAD

**Issue by vdias38** [bahmutov/next-update#141]
Hi,

it raises an error on my env

```
$ next-update
next-update@3.6.0
 - Tests if module's dependencies can be updated to the newer version without breaking the tests
 installed in folder /usr/local/lib/node_modules/next-update
checking if the current state works
up to date in 33.203s
[!] 32 vulnerabilities found [7660 packages audited]
    Severity: 4 low | 24 moderate | 4 high
    Run `npm audit` for more detail

running test command
  npm test
> meu-starter.ionic-v3@0.0.1 test /Users/victor/Dvpt/PROJECTS/meu-starter.ionic-v3
> karma start ./test-config/karma.conf.js --single-run --progress false --browsers Chrome


webpack: Compiled successfully.
webpack: Compiling...
...
> tests are passing at the start
checking NPM registry
ERROR testing next working updates
Error: timed out waiting for NPM after 10000ms
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
From previous event:
    at nextVersions (/usr/local/lib/node_modules/next-update/src/registry.js:319:10)
    at /usr/local/lib/node_modules/next-update/src/next-update.js:155:39
    at RawTask.call (/usr/local/lib/node_modules/next-update/node_modules/asap/asap.js:40:19)
    at flush (/usr/local/lib/node_modules/next-update/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I have the following installed

- osx@10.11.16
- next-update@3.6.0
- npm@6.0.0
- node@8.9.0

Please let me know if there is any more information I can give you, thanks.

**Comment by YuriiBuchchenkoDevPro** [comment]
```
$ npx next-update --help
...
  --check-version-timeout  define a custom timeout value for checking next versions     [default: 10000]
...
```

So just specify more than 10000:
```
next-update --check-version-timeout 30000
```
