### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by DanielVenturini** [bahmutov/next-update#142]
Hello everyone.
I'm new in JS and I've no idea whats is happen:

/usr/local/lib/node_modules/next-update/src/registry.js:15
const {isPrerelease} = require('./utils')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/next-update/src/next-update.js:13:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by DanielVenturini** [comment]
Oh, it's my version of NodeJs. Now it's work with current version NodeJs v6.14.3 and NPM v3.10.10.
