### ISSUE TITLE
`_ is not defined` when specifying custom test

### ISSUE THREAD

**Issue by kvz** [bahmutov/next-update#96]
```bash
ReferenceError: _ is not defined
    at test (/Users/kvz/code/invig/node_modules/next-update/src/exec-test.js:10:30)
    at /Users/kvz/code/invig/node_modules/next-update/src/next-update.js:71:57
    at RawTask.call (/Users/kvz/code/invig/node_modules/asap/asap.js:40:19)
    at flush (/Users/kvz/code/invig/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at checkCurrentInstall (/Users/kvz/code/invig/node_modules/next-update/src/next-update.js:70:10)
    at Object.<anonymous> (/Users/kvz/code/invig/node_modules/next-update/bin/next-update.js:64:3)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

I had to add `var _ = require('lodash');` to the header of `next-update/src/exec-test.js` to make things work again.

Version: 1.5.1

**Comment by bahmutov** [comment]
Also should be fixed in the NPM release that is going out right now
