### ISSUE TITLE
ReferenceError: keep is not defined

### ISSUE THREAD

**Issue by kvz** [bahmutov/next-update#97]
Just got 

```bash
ReferenceError: keep is not defined
    at /usr/local/lib/node_modules/next-update/src/test-module-version.js:95:19
    at Array.map (native)
    at installAll (/usr/local/lib/node_modules/next-update/src/test-module-version.js:84:38)
    at testInstalls (/usr/local/lib/node_modules/next-update/src/test-module-version.js:58:31)
    at RawTask.call (/usr/local/lib/node_modules/next-update/node_modules/asap/asap.js:40:19)
    at flush (/usr/local/lib/node_modules/next-update/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/next-update/bin/next-update.js:65:6)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

While running `next-update --keep --test /usr/bin/true --allow minor --tldr --latest --color --all`

On `next-update@1.5.1`

**Comment by kvz** [comment]
Perhaps it's worth mentioning that my 1.5.1 is patched with this hack to add lodash: https://github.com/bahmutov/next-update/issues/96

**Comment by bahmutov** [comment]
Should be fixed now, trying to publish to NPM new version
